import React from "react";
import {
    FaReact,
    FaNodeJs,
    FaJava,
    FaHtml5,
    FaCss3Alt,
    FaWordpress,
    FaLaravel,
    FaBootstrap,
    FaSass,
    FaVuejs,
    FaAngular,
    FaDocker,
    FaGithub,
    FaAws,
    FaCloud,
    FaGraduationCap,
    FaBriefcase,
} from "react-icons/fa";
import {
    SiCplusplus,
    SiC,
    SiGo,
    SiRust,
    SiKotlin,
    SiSwift,
    SiR,
    SiTypescript,
    SiPython,
    SiRedux,
    SiJquery,
    SiMysql,
    SiMongodb,
    SiRedis,
    SiOracle,
    SiGooglecloud,
    SiHeroku,
    SiVercel,
    SiNetlify,
    SiExpress,
    SiSpring,
    SiDjango,
    SiPhp,
    SiFlask,
    SiNestjs,
    SiGraphql,
    SiSocketdotio,
    SiMqtt,
    SiJenkins,
    SiKubernetes,
    SiJira,
    SiConfluence,
    SiTrello,
    SiWebpack,
    SiTailwindcss,
    SiChakraui,
    SiAntdesign,
    SiVite,
    SiNextdotjs,
    SiNuxtdotjs,
    SiSvelte,
    SiFirebase,
    SiSupabase,
    SiFastapi,
    SiRubyonrails,
    SiHtml5,
    SiCss3,
    SiJavascript,
    SiPrestashop,
    SiWoocommerce,
    SiGithubactions,
    SiNpm,
    SiComposer,
    SiYarn,
    SiGit,
    SiRender,
    SiPostman,
    SiHibernate,
    SiPostgresql,
} from "react-icons/si";
import { BsQuestionLg } from "react-icons/bs";
import { BiLogoSpringBoot } from "react-icons/bi";
import { IbmMq, FlowData, MessageQueue } from "@carbon/icons-react";
import { IoHardwareChip, IoFlask, IoTerminalSharp } from "react-icons/io5";

export const techIcons = {
    // Lenguajes de Programación
    javascript: <SiJavascript className="size-5 text-yellow-400" />,
    typescript: <SiTypescript className="size-5 text-blue-500" />,
    python: <SiPython className="size-4 text-blue-500" />,
    java: <FaJava className="size-5 text-red-700" />,
    php: <SiPhp className="size-5 text-blue-600" />,
    c: <SiC className="size-5 text-gray-500" />,
    cpp: <SiCplusplus className="size-5 text-blue-800" />,
    go: <SiGo className="size-5 text-cyan-400" />,
    rust: <SiRust className="size-5 text-orange-600" />,
    kotlin: <SiKotlin className="size-5 text-purple-700" />,
    swift: <SiSwift className="size-5 text-orange-400" />,
    r: <SiR className="size-5 text-blue-400" />,

    // Frontend
    react: <FaReact className="size-5 text-cyan-400" />,
    "react native": <FaReact className="size-5 text-cyan-400" />,
    redux: <SiRedux className="size-5 text-purple-500" />,
    angular: <FaAngular className="size-5 text-red-600" />,
    vue: <FaVuejs className="size-5 text-green-500" />,
    html: <FaHtml5 className="size-5 text-orange-600" />,
    html5: <SiHtml5 className="size-5 text-orange-600" />,
    css: <FaCss3Alt className="size-5 text-blue-600" />,
    css3: <SiCss3 className="size-5 text-blue-600" />,
    jquery: <SiJquery className="size-5 text-blue-700" />,
    bootstrap: <FaBootstrap className="size-5 text-purple-500" />,
    tailwindcss: <SiTailwindcss className="size-5 text-cyan-500" />,
    sass: <FaSass className="size-5 text-pink-500" />,
    "chakra-ui": <SiChakraui className="size-5 text-teal-400" />,
    "ant design": <SiAntdesign className="size-5 text-red-500" />,
    vite: <SiVite className="size-5 text-purple-600" />,
    nextjs: <SiNextdotjs className="size-5 text-black dark:text-white" />,
    nuxt: <SiNuxtdotjs className="size-5 text-green-500" />,
    svelte: <SiSvelte className="size-5 text-orange-600" />,
    jsp: <FaJava className="size-5 text-orange-400" />,

    // Backend
    nodejs: <FaNodeJs className="size-5 text-green-500" />,
    express: <SiExpress className="size-5 text-black dark:text-white" />,
    nestjs: <SiNestjs className="size-5 text-red-600" />,
    laravel: <FaLaravel className="size-5 text-red-500" />,
    spring: <SiSpring className="size-5 text-green-500" />,
    springboot: <BiLogoSpringBoot className="size-5 text-green-600" />,
    fastapi: <SiFastapi className="size-5 text-green-500" />,
    django: <SiDjango className="size-5 text-green-800" />,
    flask: <SiFlask className="size-5 text-black dark:text-white" />,
    rubyonrails: <SiRubyonrails className="size-5 text-red-700" />,

    // Bases de Datos
    mysql: <SiMysql className="size-5 text-blue-600" />,
    postgresql: <SiPostgresql className="size-5 text-blue-700" />,
    mongodb: <SiMongodb className="size-5 text-green-600" />,
    redis: <SiRedis className="size-5 text-red-600" />,
    oracle: <SiOracle className="size-5 text-red-600" />,
    supabase: <SiSupabase className="size-5 text-green-600" />,
    firebase: <SiFirebase className="size-5 text-yellow-500" />,
    hibernate: <SiHibernate className="size-5 text-gray-700 dark:text-gray-300" />,

    // CMS y E-commerce
    wordpress: <FaWordpress className="size-5 text-blue-500" />,
    prestashop: <SiPrestashop className="size-5 text-red-600" />,
    woocommerce: <SiWoocommerce className="size-10 text-purple-600" />,

    // Cloud y Despliegue
    aws: <FaAws className="size-5 text-orange-500" />,
    gcp: <SiGooglecloud className="size-5 text-yellow-500" />,
    heroku: <SiHeroku className="size-5 text-purple-600" />,
    vercel: <SiVercel className="size-5 text-black dark:text-white" />,
    netlify: <SiNetlify className="size-5 text-cyan-400" />,
    render: <SiRender className="size-5 text-lime-500" />,
    docker: <FaDocker className="size-5 text-blue-500" />,
    kubernetes: <SiKubernetes className="size-5 text-blue-500" />,

    // Integración y Mensajería
    rest: <FaCloud className="size-5 text-blue-500" />,
    soap: <FaCloud className="size-5 text-indigo-500" />,
    graphql: <SiGraphql className="size-5 text-pink-500" />,
    socketio: <SiSocketdotio className="size-5 text-black dark:text-white" />,
    mqtt: <SiMqtt className="size-5 text-purple-600" />,
    soa: <FlowData size={20} className="text-gray-600 dark:text-gray-400" />,
    "ibm integration bus": <IbmMq size={20} className="text-blue-700" />,
    "websphere message broker": <MessageQueue size={20} className="text-blue-700" />,

    // Control de Versiones y CI/CD
    git: <SiGit className="size-5 text-orange-600" />,
    github: <FaGithub className="size-5 text-black dark:text-white" />,
    "github actions": <SiGithubactions className="size-5 text-blue-500" />,
    jenkins: <SiJenkins className="size-5 text-orange-500" />,

    // Herramientas y Miscelánea
    npm: <SiNpm className="size-5 text-red-600" />,
    composer: <SiComposer className="size-5 text-gray-200 " />,
    yarn: <SiYarn className="size-5 text-blue-500" />,
    webpack: <SiWebpack className="size-5 text-blue-500" />,
    jira: <SiJira className="size-5 text-blue-600" />,
    confluence: <SiConfluence className="size-5 text-blue-700" />,
    trello: <SiTrello className="size-5 text-blue-600" />,
    postman: <SiPostman className="size-5 text-orange-500" />,

    // Conceptos
    iot: <IoHardwareChip className="size-5 text-green-700 dark:text-green-700" />,
    scripting: <IoTerminalSharp className="size-5 text-gray-600 dark:text-gray-400" />,
    "formación en ti": <FaGraduationCap className="size-5 text-yellow-500" />,
    "innovación en ciencia": <IoFlask className="size-5 text-lime-500" />,
    "soporte funcional": <FaBriefcase className="size-5 text-blue-500" />,
};

export const getTechIcon = (techName) => {
    return techIcons[techName.toLowerCase()] || <BsQuestionLg className="size-5 text-gray-400" />;
};
